trigger:
  branches:
    include:
      - feature-ms-joelMora-mensaje

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: Compilacion

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/reports/xml/jacoco'
    pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java'
    reportDirectory: '$(System.DefaultWorkingDirectory)/build/reports/tests'
    failIfCoverageEmpty: true